# Generated by Django 4.2.5 on 2023-11-29 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSocio', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(80)], verbose_name='Nombre Socio')),
                ('fechaIncorporacion', models.DateField(verbose_name='Fecha de Incorporacion')),
                ('añoNacimiento', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año de Nacimiento')),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(9)])),
                ('correo', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('SUSPENDIDO', 'Suspendido'), ('RETIRADO', 'Retirado')], max_length=15)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('NO BINARIO', 'No Binario')], max_length=15)),
                ('observacion', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
